# Generated by Django 3.2 on 2022-04-18 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_auto_20220413_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mac_adress',
            field=models.CharField(default=111111111111, max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^[A-Z0-9]*$')]),
        ),
    ]
