# Generated by Django 3.2 on 2022-04-18 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_account_mac_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mac_adress',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^[A-Z0-9]*$')]),
        ),
    ]
