# Generated by Django 3.2 on 2022-04-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_alter_account_mac_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100)),
            ],
        ),
    ]
