# Generated by Django 3.2 on 2022-05-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0005_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='mac',
            name='mac2',
            field=models.CharField(default='aaaaaaaaaaaaa', max_length=100),
        ),
    ]
