# Generated by Django 3.2 on 2022-05-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0006_mac_mac2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='mac2',
            field=models.CharField(max_length=100),
        ),
    ]
