# Generated by Django 3.2 on 2022-05-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0010_auto_20220530_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='MACsikibetu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_s', models.CharField(default='000000000000', max_length=100)),
                ('mac2', models.CharField(default='000000000000', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='syusseki_Nissu',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
