# Generated by Django 3.2 on 2022-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0011_auto_20220530_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='syusseki_Nissu',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='macsikibetu',
            name='mac2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='macsikibetu',
            name='mac_s',
            field=models.CharField(max_length=100),
        ),
    ]
