# Generated by Django 3.2 on 2022-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0012_auto_20220530_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='syusseki_Nissu',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
