# Generated by Django 3.2 on 2022-06-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0013_alter_account_syusseki_nissu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='syusseki_state',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='zaisitu_state',
            field=models.CharField(max_length=4),
        ),
    ]
